package main

func main() {
	testMap()
	// testSlice1()
	// testSlice2()
	// testNoCopy()
	// testCtx1()
	// testCtx2()
	// testCtx3()
	// testCtx()
	// testErrGroup()
	// testOnce()
	// textCtxCancel2()
	// testSortBool([]bool{false, false, true, true, false, false, true})
	// testError()
	// testMapSliCap()
	// testPanic()
	// testPanic1()
	// testPanic2()
	// testInheritance()
	// testCancelCtx()
	// testCancelCtx1()
	// checkChannelClosed()
	// testMapSort()
	// testComplexData()
	// testNilMapOrSlice()
	// testCap()
	// testBits()
	// testStringSplit()
	// testDecimal()
	// testLangTrans()
	// Test_if()
	// TestAppend()
	// TestChannel()
	// testInt()
	// testEmptyArray()
	// TestSkills()
	// TestPipeline()
	// testDefer()
	// testCtx4()
	// testDefer1()
	// isNil()
}
