package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Println("CPU:-----", runtime.NumCPU(), "\n")
	// TestBoolean()
	// testIface()
	// testMap()
	// testStr()
	// TestSli()
	// testSlice1()
	// testSlice2()
	// testSlice3()
	// testNoCopy()
	// testCtx1()
	// testCtx2()
	// testCtx3()
	// testCtx()
	// testErrGroup()
	// testOnce()
	// textCtxCancel2()
	// testSortBool([]bool{false, false, true, true, false, false, true})
	// testError()
	// testMapSliCap()
	// testPanic()
	// testPanic1()
	// testPanic2()
	// testInheritance()
	// testCancelCtx()
	// testCancelCtx1()
	// checkChannelClosed()
	// testMapSort()
	// testComplexData()
	// testNilMapOrSlice()
	// testCap()
	// testBits()
	// testStringSplit()
	// testDecimal()
	// testLangTrans()
	// Test_if()
	// TestAppend()
	// TestChannel()
	// testInt()
	// testEmptyArray()
	// TestSkills()
	// TestPipeline()
	// testDefer()
	// testCtx4()
	// testDefer1()
	// isNil()
	// testTypeSize()
	// testTicker()
	// testIOTA()
	// TestObjSize()
	// TestSyncPool()
	// TestNonPool()
	// TestDiff()
	// fff()
	// testSize()
	// getAllMonthLastDay(2024)
	// EqualSli([]int{1, 2, 3}, []int{1, 2,3})
	// EqualSli([]int{1, 2, 3}, []int{1, 3,2})
	// testStringFunc()
	// testDeferOrder()
	// testWaitGroup()
	// testMMAdd()
	// testMapInit()
	// testCalculation()
	// test_getLastDayOfYearMonth(2024)
	// testSortTime()
	// testSyncMap()
	// testFormatTime()
	// testSyncSafetyForSlice()
	// TestTime()
	// testRound()
	// testJSON()
	TestOverflow()
}
